# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM golang:1.23.2-bookworm AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY byteorder ./byteorder
COPY payload ./payload
COPY cmd/server ./cmd/server

ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -trimpath -ldflags="-s -w" -o /out/kubezonnet-server ./cmd/server

FROM cgr.dev/chainguard/static
COPY --from=builder /out/kubezonnet-server /kubezonnet-server
ENTRYPOINT ["/kubezonnet-server"]
